### ISSUE TITLE
Install script didnt compile .exe

### ISSUE THREAD

**Issue by kh-v-git** [kenwdelong/frog#1]
During compile I have this error

SetOutPath: "$INSTDIR"
File: "..\Frog3.exe" -> no files found.
Usage: File [/nonfatal] [/a]([/r] [/x filespec [...]] filespec [...] |
   /oname=outfile one_file_only)
Error in script "C:\Users\VS\Downloads\frog-master\frog-master\FROG\installer\Installer.nsi" on line 107 -- aborting creation process

**Comment by kenwdelong** [comment]
Yeah, there's no compiled binary in the repo.  You'd have to buy Embarcadero Delphi to actually compile it.

Check the site in a little while; I'm going to put the executables on DropBox and link to them from the site.

##  

Ken DeLong   kenwdelong@yahoo.com
Life is complex: it has both real and imaginary parts.
Aung San Suu Kyi is a PARLIAMENTARIAN!!

**Comment by kenwdelong** [comment]
See the link in the ReadMe file
