### ISSUE TITLE
How are the temporal and spectral FWHMs calculated?

### ISSUE THREAD

**Issue by davidjamesromano** [kenwdelong/frog#5]
In the results tab, the temporal and spectral FWHMs are displayed, but to what type of function are the FWHMs describing? I'm assuming Gaussian, but there is no mention of it in the help files, at least for what I've found. I don't exactly speak Pascal either, so I figured this might be the fastest way to find out.

**Comment by davidjamesromano** [comment]
Never mind! I figured it out. Looks like it is a Gaussian FWHM, if I'm not mistaken.

**Comment by kenwdelong** [comment]
If I remember correctly, to find the FWHM in either time or spectral domain, the code starts out at the edges of a normalized intensity curve and works it's way back toward the center until it gets to intensity 0.5.  It's not a super useful measurement if the pulse has a lot of structure, but it does give some idea of it's width.

**Comment by kenwdelong** [comment]
Yeah, found it!  https://github.com/kenwdelong/frog/blob/master/FROG/Func1D.pas#L205

Boy, I haven't looked at that code for a long time!

**Comment by davidjamesromano** [comment]
Ah! That make sense. Thank you for uploading this and for looking into my question. Cheers!

**Comment by davidjamesromano** [comment]
Also, the documentation and tutorial PDF are so incredibly helpful! <3
